# Generated by Django 4.0.1 on 2022-03-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdeateails',
            name='balance',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialdeateails',
            name='goals',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialdeateails',
            name='income',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialdeateails',
            name='loans',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='financialdeateails',
            name='savaing',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
