# Generated by Django 4.0.1 on 2022-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('precent', models.IntegerField()),
            ],
        ),
    ]
